; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
   default_envs = esp32dev

; You MUST inject these options into [env:] section
; using ${common.***} (see below)
[common]
    framework = arduino

   lib_deps = 
      ; https://github.com/ovace/ESPutils.git
      Ticker
      ; Wire
      ; khoih-prog/ESPAsync_WiFiManager @ ^1.9.1
      ; ESPAsyncTCP
      ; me-no-dev/ESP Async WebServer @ ^1.2.3
      ; ayushsharma82/AsyncElegantOTA @ ^2.2.5
      ; AsyncMqttClient	
      bblanchon/ArduinoJson @ ^6.17.0
      arduino-libraries/ArduinoHttpClient @ ^0.4.0
      ; arduino-libraries/NTPClient @ ^3.1.0
      adafruit/Adafruit Unified Sensor
      adafruit/DHT sensor library @^1.4.0
      claws/BH1750 @ ^1.2.0
      adafruit/Adafruit BME280 Library @ ^2.1.2        
      knolleary/PubSubClient @ ^2.8  
        
        
      
[env:esp32dev]      
   board = esp32dev
   platform = espressif32
   framework = ${common.framework}
   lib_ldf_mode = chain+
   ; Library options
   lib_deps =
      ; Original for wsp32     
      ${common.lib_deps}       
      ; ldab/esp32_ftpclient @ 0.1.3
      ; lorol/LittleFS_esp32 @ ^1.0.6

[env:esp01_4m]
   platform = espressif8266
   board = esp01_1m
   framework = arduino
   board_build.filesystem = littlefs
   board_build.ldscript = eagle.flash.4m3m.ld
   ;extra_scripts =
   ;    pre:extra_script.py

   ; Library options
   lib_deps =
      ${common.lib_deps}
      ; ${common.lib_deps_builtin}
      ; ${common.lib_deps_external}    

   board_build.mcu = esp8266
   board_build.f_cpu = 80000000L

   ; Serial Monitor options
   ; Serial Monitor options
   monitor_speed = 115200
   monitor_flags = default, colorize, esp8266_exception_decoder
   monitor_port = COM3

[env:esp01_1m]
   platform = espressif8266
   board = esp01_1m
   framework = arduino
   board_build.filesystem = littlefs
   ;extra_scripts = pre:extra_script.py

   ; Library options
   lib_deps =
      ${common.lib_deps_builtin}
      ${common.lib_deps_external}    

   board_build.mcu = esp8266
   board_build.f_cpu = 80000000L

   ; Serial Monitor options
   monitor_speed = 
      ${common.monitor_speed}
   monitor_flags = 
      ${common.monitor_flags), esp8266_exception_decoder
   monitor_port = 
      ${common.monitor_port}



[env:esp01_4m-OTA]
   platform = espressif8266
   board = esp01_1m
   framework = arduino
   board_build.filesystem = littlefs
   board_build.ldscript = eagle.flash.4m3m.ld
   ; Library options
   lib_deps =
      ${common.lib_deps_builtin}
      ${common.lib_deps_external}    

   board_build.mcu = esp8266
   board_build.f_cpu = 80000000L
   ; Serial Monitor options
   monitor_speed = 
      ${common.monitor_speed}
   monitor_flags = 
      ${common.monitor_flags), esp8266_exception_decoder
   monitor_port = 
      ${common.monitor_port}
   upload_protocol = espota
   ; "ESP-5B8D36" = "ESP3" // Level0
   ; "ESP-5AE2E7" = "ESP7" // Level1
   ; "ESP-0E939F" = "ESP1"
   ; ""
   upload_port = "ESPSW01"
   upload_flags = -p 8266

[env:esp01_1m-OTA]
   platform = espressif8266
   board = esp01_1m
   framework = arduino
   board_build.filesystem = littlefs
   ; Library options
   lib_deps =
      ${common.lib_deps_builtin}
      ${common.lib_deps_external}    

   board_build.mcu = esp8266
   board_build.f_cpu = 80000000L
   ; Serial Monitor options
   monitor_speed = 
      ${common.monitor_speed}
   monitor_flags = 
      ${common.monitor_flags), esp8266_exception_decoder
   monitor_port = 
      ${common.monitor_port}
   upload_protocol = espota
   ; "ESP-5B8D36" = "ESP3" // Level0
   ; "ESP-5AE2E7" = "ESP7" // Level1
   ; "ESP-0E939F" = "ESP1"
   ; ""
   upload_port = "ESPSW02"
   upload_flags = -p 8266

